apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.airflow.scheduler_name }}
  namespace: {{ .Values.airflow.infra_namespace }}
  labels:
    app: {{ .Values.airflow.scheduler_name }}
    chart: {{ include "airflow.labels.chart" . }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Values.airflow.scheduler_name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.airflow.scheduler_name }} # has to match .spec.template.metadata.labels
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.airflow.scheduler_name }} # has to match .spec.selector.matchLabels
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: {{ .Values.storage.volume_name }}
          persistentVolumeClaim:
            claimName: {{ .Values.storage.pvc_name }}
      containers:
        - name: {{ .Values.airflow.scheduler_name }}-container
          image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
          {{ if ne .Values.cluster_type "dev" }}
          resources:
            requests:
              memory: "1000Mi"
              cpu: "0.25"
            limits:
              memory: "1000Mi"
              cpu: "1"
          {{ end }}
          envFrom:
          - configMapRef:
              name: {{ .Values.airflow.config_map }}
          command: [ "bash" ]
          args: [ "/airflow-bin/start_scheduler.sh"]
          volumeMounts:
            - mountPath: {{ .Values.storage.volume_mount_path }}
              name: {{ .Values.storage.volume_name }}
      imagePullSecrets:
        - name: regcred


