###################################
# Cluster Type
###################################
cluster_type: aks

###################################
# Airflow - Common Configs
###################################
airflow:
  infra_namespace: dpaas
  scheduler_name: dsct-airflow-scheduler-aks
  webserver_name: dsct-airflow-webserver-aks
  git_sync_name: dsct-airflow-git-sync-aks
  config_map: dsct-airflow-env-vars-configmap-aks
  statsd_exporter_name: dsct-airflow-statsd-exporter-aks
  image:
    repository: dummy
    tag: latest

###################################
# Airflow - Scheduler Configs
###################################
scheduler:
  core:
    executor: KubernetesExecutor
    dags_are_paused_at_creation: "\"True\""
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    failureThreshold: 5

###################################
# Kubernetes - Service Account
###################################
serviceAccount:
  name: "dsct-airflow-service-account"

######################################
# Kubernetes - Pod operator management
######################################
kubernetes:
  delete_worker_pods: "\"True\""
  delete_worker_pods_on_failure: "\"True\""

###################################
# DB
###################################
#db:
#  name: "dsct-airflow-db"
#  db_user: "airflow_db_user"
#  db_password: "airflow_db_password"
#  db_name: "dsct_airflow_db"
#  db_connection_string: "postgresql+psycopg2://airflow_db_user:airflow_db_password@dsct-airflow-db:5432/dsct_airflow_db"
#  image:
#    repository: ihorton/dpaas_airflow
#    tag: postgres-12.3

db:
  db_user: "dpaas_airflow@dpaas-airflow"
  db_password: "IanHorton1"
  db_name: "airflow_dsct"
  db_connection_string: "postgresql+psycopg2://dpaas_airflow@dpaas-airflow:IanHorton1@dpaas-airflow.postgres.database.azure.com:5432/airflow_dsct"



###################################
# Storage
###################################
storage:
  pvc_name: dsct-airflow-aks-persistent-volume-claim
  volume_name: dsct-airflow-volume
  volume_mount_path: "/dsct-airflow-volume/"

###################################
# Webserver
###################################
webserver:
  base_url: http://localhost:80