###################################
# Cluster Type
###################################
cluster_type: dev

###################################
# Airflow - Common Configs
###################################
airflow:
  infra_namespace: dpaas
  scheduler_name: dsct-airflow-scheduler
  webserver_name: dsct-airflow-webserver
  git_sync_name: dsct-airflow-git-sync
  config_map: dsct-airflow-env-vars-configmap
  statsd_exporter_name: dsct-airflow-statsd-exporter
  image:
    repository: localhost:5000/dsct-airflow-image-2.1.1
    tag: latest

###################################
# Airflow - Scheduler Configs
###################################
scheduler:
  core:
    executor: KubernetesExecutor
    dags_are_paused_at_creation: "\"True\""
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 30
    failureThreshold: 5


###################################
# Kubernetes - Service Account
###################################
serviceAccount:
  name: "dsct-airflow-service-account"

######################################
# Kubernetes - Pod operator management
######################################
kubernetes:
  delete_worker_pods: "\"False\""
  delete_worker_pods_on_failure: "\"False\""


###################################
# DB
###################################
db:
  name: "dsct-airflow-db"
  db_user: "airflow_db_user"
  db_password: "airflow_db_password"
  db_name: "dsct_airflow_db"
  db_connection_string: "postgresql+psycopg2://airflow_db_user:airflow_db_password@dsct-airflow-db:5432/dsct_airflow_db"
  image:
    repository: localhost:5000/postgres
    tag: 12.3

###################################
# Storage
###################################
storage:
  pvc_name: dsct-airflow-pvc
  volume_name: dsct-airflow-volume
  volume_mount_path: "/dsct-airflow-volume/"


###################################
# Webserver
###################################
webserver:
  base_url: http://localhost:80
