apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.airflow.config_map }}
  namespace: {{ .Values.airflow.infra_namespace }}
data:
  CLUSTER_TYPE: {{ .Values.cluster_type }}
  AIRFLOW__CORE__EXECUTOR: {{ .Values.scheduler.core.executor }}
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: {{ .Values.db.db_connection_string }}
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: {{ .Values.scheduler.core.dags_are_paused_at_creation }}
  AIRFLOW__WEBSERVER__BASE_URL: {{ .Values.webserver.base_url }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: {{ .Values.airflow.image.repository }}
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: {{ .Values.airflow.image.tag }}
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: {{ .Values.serviceAccount.name }}
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: {{ .Values.kubernetes.delete_worker_pods }}
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE: {{ .Values.kubernetes.delete_worker_pods_on_failure }}
