apiVersion: v1
appVersion: 1.0.0
description: DSCT airflow
home: https://stash.corp.appnexus.com/projects/DATA_SCIENCE/repos/app_dsct-airflow/browse
name: airflow
sources:
- https://stash.corp.appnexus.com/projects/DATA_SCIENCE/repos/app_dsct-airflow/browse
version: 1.0.1
